Add some links from jobs.cz team
lmc-eu/awesome-developer pull request #1
Opened 2018-04-11 10:21 UTC by jirinovak

2018-04-11 11:11 UTC, OndraM requested changes

2018-04-11 11:11 UTC, OndraM commented on README.md
> +- [@Ocramius - Fluent interfaces are evil](https://ocramius.github.io/blog/fluent-interfaces-are-evil/)
What about swap author and article title? The title is more important imo. (The same below)

2018-04-11 11:11 UTC, OndraM commented on README.md
> +- [Symfony komponenty](https://www.zdrojak.cz/serialy/symfony-po-kruckach/)
I'd create somethinglike "PHP specific" subsection as part of this section and put this Symfony topic here (And I think more will come). The other links are language-independent.

2018-04-11 11:11 UTC, OndraM commented on README.md
> +- [Core review](#code-review)
typo, s/Core/Code/

2018-04-11 11:11 UTC, OndraM commented on README.md
> +    - https://www.ibuildings.nl/blog/2016/01/programming-guidelines-php-developers-part-1-reducing-complexity
Links are broken, also we can show add here their title via markdown, to not show just the URL.

Proper links:
- https://www.ibuildings.nl/blog/2016/01/programming-guidelines-part-1-reducing-complexity
- https://www.ibuildings.nl/blog/2016/01/programming-guidelines-part-2-getting-rid-null
Third one is OK :)

2018-04-11 11:11 UTC, OndraM commented on README.md
> +- [Newsletter](#newsletters)
Newsletters

2018-04-11 11:11 UTC, OndraM commented on README.md
> +- [Jak a proč fixupovat](https://filip-prochazka.com/blog/git-fixup )
unnecessary space

2018-04-11 11:29 UTC, OndraM approved these changes

2018-04-12 07:39 UTC, legendik approved these changes

2018-04-12 11:13 UTC, merged