Add more articles
lmc-eu/awesome-developer pull request #3
Opened 2018-04-12 13:33 UTC by MortalFlesh

2018-04-12 14:16 UTC, OndraM requested changes

2018-04-12 14:16 UTC, OndraM commented on README.md
> +- [Fractal of bad design](http://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/)
I know this article, it *was* interesting, but IMHO article from 2012 (PHP 5.4 was the newest then)  is no longer relevant nowadays (and maybe adds much more confusion - "There is no finally construct", "PHP errors cannot be caught with try/catch", "Array unpacking can be done with the list($a, $b) " and like half of the article is outdated and wrong for PHP 7.1+).

2018-04-12 14:16 UTC, OndraM commented on README.md
> +- [Formatting exceptions](http://rosstuck.com/formatting-exception-messages/)
I know another nice article about this topic (exceptions in PHP), could you please remove this from the PR and we can have have a separate discussion elsewhere (maybe create in issue and wa can post our suggestions there)? So we don't add both of them, as they may cover the same topic.

2018-04-12 14:16 UTC, OndraM commented on README.md
> +- [Doctrine hydratation optimization](https://ocramius.github.io/blog/doctrine-orm-optimization-hydration/)
I'm not saying this is not interesting theory (it is!), but I'm not convinced this should be part of "articles essential to read" - this is very specialized topic about Doctrine internals.

2018-04-12 14:16 UTC, OndraM commented on README.md
> +- [PHPUnit - best practices](https://thephp.cc/news/2016/02/questioning-phpunit-best-practices)
IMO this is no longer and issue - the old syntax was removed from new PHPUnit and [codestyle](https://github.com/lmc-eu/php-coding-standard/) forbids the annotations. So I think we are already covered :).

2018-04-12 14:16 UTC, OndraM commented on README.md
> +- [Giving better code review](https://medium.com/@mrjoelkemp/giving-better-code-reviews-16109e0fdd36)
Dtto, I suggest putting this to separate PR, maybe we can find other CR-related articles and we could include only the "best" one.

2018-04-12 14:16 UTC, OndraM commented on README.md
> +- [Technický dluh](http://blog.think-forth.com/2016/01/21/technicky-dluh/)
Nice one, I didn't know it, it sums the nice things :+1: .

2018-04-12 14:16 UTC, OndraM commented on README.md
> +- [Functional programming](https://speakerdeck.com/pwm/functional-programming-in-php)
Also a nice topic. But don't you think this is very "pro" one? I'm not sure its worth it to confuse newcommers and junior-devs with this concepts, and PHP is not functional language, so "FP in PHP" is by definition not an essential knowledge.

But I think we may add something more introductory to basic FP concepts. Don't you know any (short) interesting article about this?

2018-04-13 07:23 UTC, closed without merging

2018-04-13 07:24 UTC, MortalFlesh commented
ok i will send it separately by article