Add extremely Defensive PHP
lmc-eu/awesome-developer pull request #8
Opened 2018-05-22 09:06 UTC by legendik

2018-05-22 09:37 UTC, OndraM requested changes
This is nice presentation, heard it on WebExpo, so I'm +1 to include it in the list. However it is PHP-specific, so I'd move it there.

Also could you please include short description ("Add short description why the resource is awesome. The description sentence should end by a dot.")
Thanks :)

2018-05-25 10:15 UTC, MortalFlesh approved these changes

2018-05-25 10:23 UTC, OndraM approved these changes

2018-05-25 10:24 UTC, merged

2018-05-25 10:24 UTC, OndraM commented
Thanks @legendik!